const steps=[
{id:'style',label:'스타일',icon:'◌',title:'이미지 스타일',hint:'결과물의 전체적인 시각 언어를 정해요.',placeholder:'예: 따뜻한 수채화 일러스트',options:[['photorealistic','포토리얼','Photorealistic'],['cinematic photography','시네마틱','Cinematic'],['editorial fashion photography','패션 화보','Editorial'],['soft watercolor illustration','수채화','Watercolor'],['oil painting','유화','Oil'],['pencil drawing','연필 드로잉','Pencil'],['Japanese anime illustration','애니메이션','Anime'],['detailed 3D render','3D 렌더','3D render']]},
{id:'character',label:'캐릭터',icon:'♙',title:'캐릭터와 인물',hint:'주인공의 정체성과 분위기를 설명해요.',placeholder:'예: 20대 한국인 여성, 차분하고 지적인 분위기',options:[['a young adult East Asian woman','동아시아 여성','Young adult'],['a young adult East Asian man','동아시아 남성','Young adult'],['a stylish fantasy heroine','판타지 히로인','Fantasy'],['a futuristic space explorer','우주 탐험가','Sci-fi'],['a cute anthropomorphic cat','의인화 고양이','Character'],['a mysterious forest spirit','숲의 정령','Mystical']]},
{id:'face',label:'얼굴',icon:'◎',title:'얼굴과 표정',hint:'얼굴형, 이목구비, 표정을 구체화해요.',placeholder:'예: 계란형 얼굴, 아몬드형 눈, 은은한 미소',options:[['delicate oval face and almond-shaped eyes','섬세한 계란형','Almond eyes'],['soft round face and bright eyes','부드러운 둥근형','Bright eyes'],['defined facial features and a sharp jawline','선명한 윤곽','Sharp jawline'],['a calm, confident expression','차분한 자신감','Confident'],['a warm natural smile','자연스러운 미소','Warm smile'],['a mysterious, thoughtful expression','신비로운 표정','Thoughtful'],['natural light makeup','옅은 화장','Natural']]},
{id:'hair',label:'헤어',icon:'≈',title:'헤어스타일',hint:'길이, 컬러, 질감과 앞머리를 정해요.',placeholder:'예: 긴 검은 생머리, 시스루 뱅',options:[['long, softly waved black hair','긴 웨이브 흑발','Long · Black'],['long platinum-blonde hair','긴 백금발','Long · Blonde'],['sleek, straight black bob','단정한 흑발 단발','Bob · Black'],['short textured brown hair','짧은 갈색 머리','Short · Brown'],['a loose, elegant updo','느슨한 업스타일','Elegant'],['curly auburn hair with wispy bangs','곱슬 적갈색 헤어','Curly · Auburn'],['long hair gathered into a high ponytail','묶은 머리','Ponytail'],['woven into delicate braids','땋은 머리','Braids'],['medium-length textured crop','짧은 남성 머리','Short Male'],['medium-length side part','가르마','Side-part'],['full shave bald look','민머리','Bald look']]},
{id:'outfit',label:'의상',icon:'◇',title:'의상과 소품',hint:'소재, 컬러, 스타일을 함께 표현해요.',placeholder:'예: 아이보리 재킷과 심플한 검정 드레스',options:[['an ivory tailored jacket over a simple black dress','아이보리 재킷','Modern formal'],['a flowing white linen dress','화이트 린넨 드레스','Natural'],['a classic black suit with a silk shirt','클래식 블랙 수트','Formal'],['a white button-down shirt and black dress pants','오피스 룩','Office'],['a black high-waisted pleated miniskirt','검정색 미니스커트','Miniskirt'],['a layered futuristic silver outfit','퓨처리즘 실버 룩','Futuristic'],['a cozy oversized knit and denim','오버핏 니트와 데님','Casual'],['an ornate fantasy cloak with subtle embroidery','자수 판타지 망토','Fantasy']]},
{id:'pose',label:'포즈',icon:'⌁',title:'포즈와 시선',hint:'몸의 움직임과 카메라를 향한 시선을 정해요.',placeholder:'예: 자연스럽게 서서 카메라를 바라보는 모습',options:[['standing naturally and looking directly at the camera','자연스럽게 서기','Camera gaze'],['walking naturally with a subtle sense of motion','자연스럽게 걷기','In motion'],['sitting with a relaxed, elegant posture','편안하게 앉기','Relaxed'],['looking over one shoulder','어깨 너머 응시','Over shoulder'],['a dynamic action pose with balanced anatomy','역동적인 액션','Dynamic'],['a candid side profile, looking into the distance','자연스러운 측면','Candid']]},
{id:'scene',label:'배경',icon:'⌂',title:'배경과 분위기',hint:'장소, 시간, 날씨, 감정을 설계해요.',placeholder:'예: 해 질 무렵 서울의 조용한 루프탑 정원',options:[['a quiet Seoul rooftop garden at blue hour','서울 루프탑','Blue hour'],['a sunlit minimalist photo studio','미니멀 스튜디오','Soft daylight'],['a misty forest filled with soft morning light','안개 낀 숲','Morning'],['a neon-lit futuristic city at night','네온 미래 도시','Night'],['a warm Mediterranean seaside village','지중해 해변 마을','Golden hour'],['a grand old library with dust in the light','고풍스러운 도서관','Atmospheric']]},
{id:'camera',label:'촬영',icon:'▣',title:'촬영과 디테일',hint:'구도, 렌즈, 조명, 화면비를 마무리해요.',placeholder:'예: 허리 위 인물 사진, 얕은 심도, 4:5 세로 비율',options:[['waist-up portrait, eye-level angle, 85mm lens, shallow depth of field, vertical 4:5 composition','허리 위 인물','85mm · 4:5'],['full-body shot, eye-level angle, natural perspective, vertical 3:4 composition','전신 촬영','Full body · 3:4'],['cinematic wide shot, 35mm lens, horizontal 16:9 composition','시네마틱 와이드','35mm · 16:9'],['intimate close-up, 105mm lens, soft bokeh','클로즈업','105mm · Bokeh'],['low-angle composition with dramatic rim lighting','로우 앵글','Dramatic'],['top-down composition with clean balanced spacing','탑뷰','Graphic']]}];

const state={active:0,selected:{},custom:{}};const tabsEl=document.getElementById('stepTabs'),cardEl=document.getElementById('stepCard'),outputEl=document.getElementById('promptOutput'),toastEl=document.getElementById('toast');
function preserveInput(text){return text.trim()}
function renderTabs(){tabsEl.innerHTML=steps.map((s,i)=>`<button class="step-tab ${i===state.active?'active':''}" type="button" data-step="${i}" aria-current="${i===state.active?'step':'false'}"><span class="num">0${i+1}</span>${s.label}</button>`).join('');tabsEl.querySelectorAll('.step-tab').forEach(b=>b.onclick=()=>{state.active=+b.dataset.step;renderTabs();renderCard()})}
function renderCard(){const s=steps[state.active],selected=state.selected[s.id];cardEl.innerHTML=`<div class="step-title-row"><span class="step-icon">${s.icon}</span><div><h2>${s.title}</h2><p>${s.hint}</p></div></div><div class="option-grid">${s.options.map(([v,ko,en])=>`<button class="option ${selected===v?'selected':''}" type="button" data-value="${v}"><strong>${ko}</strong><small>${en}</small></button>`).join('')}</div><div class="custom-field"><label for="customInput">직접 입력 <span class="field-kicker">AS ENTERED</span></label><textarea id="customInput" rows="2" placeholder="${s.placeholder}">${state.custom[s.id]||''}</textarea><p class="helper">입력한 한글은 번역하지 않고 결과 프롬프트에 그대로 반영됩니다.</p></div>`;cardEl.querySelectorAll('.option').forEach(b=>b.onclick=()=>{state.selected[s.id]=state.selected[s.id]===b.dataset.value?'':b.dataset.value;renderCard();updatePrompt();saveDraft()});document.getElementById('customInput').oninput=e=>{state.custom[s.id]=e.target.value;updatePrompt();saveDraft()}}
function buildPrompt(){const parts=[];steps.forEach(s=>{const v=[state.selected[s.id],preserveInput(state.custom[s.id]||'')].filter(Boolean);if(v.length)parts.push(v.join(', '))});if(!parts.length)return'왼쪽에서 원하는 항목을 선택하거나 직접 입력하세요. 완성된 프롬프트가 여기에 표시됩니다.';return`${parts.join('. ')}. highly detailed, cohesive visual storytelling, natural anatomy, refined composition, professional quality.`}
function updatePrompt(){outputEl.value=buildPrompt();document.getElementById('wordCount').textContent=`${outputEl.value.trim().split(/\s+/).filter(Boolean).length} words`}
function showToast(m){toastEl.textContent=m;toastEl.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toastEl.classList.remove('show'),2200)}
async function copyText(text,m='클립보드에 복사했어요.'){try{await navigator.clipboard.writeText(text)}catch{outputEl.select();document.execCommand('copy')}showToast(m)}
function saveDraft(){localStorage.setItem('museform-draft',JSON.stringify(state))}function loadDraft(){try{const d=JSON.parse(localStorage.getItem('museform-draft'));if(d)Object.assign(state,d);delete state.negative}catch{}}
function saveHistory(){const h=JSON.parse(localStorage.getItem('museform-history')||'[]');h.unshift({prompt:outputEl.value,date:new Date().toISOString()});localStorage.setItem('museform-history',JSON.stringify(h.slice(0,8)));document.getElementById('saveBtn').classList.add('saved');document.getElementById('saveBtn').textContent='♥';showToast('최근 프롬프트에 저장했어요.')}
function renderHistory(){const h=JSON.parse(localStorage.getItem('museform-history')||'[]'),list=document.getElementById('historyList');list.innerHTML=h.length?h.map((x,i)=>`<button class="history-item" type="button" data-index="${i}"><p>${x.prompt.slice(0,180)}${x.prompt.length>180?'…':''}</p><time>${new Date(x.date).toLocaleString('ko-KR')}</time></button>`).join(''):'<div class="empty-history">아직 저장한 프롬프트가 없어요.</div>';list.querySelectorAll('.history-item').forEach(x=>x.onclick=()=>{outputEl.value=h[+x.dataset.index].prompt;document.getElementById('historyDialog').close();showToast('저장된 프롬프트를 불러왔어요.')})}
function fill(){state.selected={style:'editorial fashion photography',character:'a young adult East Asian woman',face:'a calm, confident expression',hair:'long, softly waved black hair',outfit:'an ivory tailored jacket over a simple black dress',pose:'standing naturally and looking directly at the camera',scene:'a quiet Seoul rooftop garden at blue hour',camera:'waist-up portrait, eye-level angle, 85mm lens, shallow depth of field, vertical 4:5 composition'};renderCard();updatePrompt();saveDraft();showToast('에디토리얼 프리셋을 채웠어요.')}
document.getElementById('copyBtn').onclick=()=>{copyText(outputEl.value);const l=document.querySelector('#copyBtn span:last-child');l.textContent='복사 완료';setTimeout(()=>l.textContent='프롬프트 복사',1800)};document.getElementById('saveBtn').onclick=saveHistory;document.getElementById('surpriseBtn').onclick=fill;document.getElementById('resetBtn').onclick=()=>{state.selected={};state.custom={};renderCard();updatePrompt();saveDraft();showToast('새 프롬프트를 시작합니다.')};document.getElementById('historyBtn').onclick=()=>{renderHistory();document.getElementById('historyDialog').showModal()};document.getElementById('closeHistoryBtn').onclick=()=>document.getElementById('historyDialog').close();document.getElementById('closeApiBtn').onclick=()=>document.getElementById('apiDialog').close();document.getElementById('copyApiPromptBtn').onclick=()=>{copyText(outputEl.value);document.getElementById('apiDialog').close()};
document.getElementById('generateBtn').onclick=async()=>{const endpoint=window.MUSEFORM_IMAGE_ENDPOINT;if(!endpoint){document.getElementById('apiDialog').showModal();return}const b=document.getElementById('generateBtn');b.classList.add('loading');b.innerHTML='<span>✦</span> 이미지를 생성하고 있어요…';try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:outputEl.value})});if(!r.ok)throw Error();const d=await r.json();document.querySelector('#imageStage img').src=d.imageUrl||`data:image/png;base64,${d.b64_json}`;document.querySelector('.sample-pill').textContent='GENERATED';document.getElementById('apiNote').textContent='현재 프롬프트로 생성된 이미지입니다.';showToast('이미지 생성이 완료됐어요.')}catch{showToast('이미지 생성 서버를 확인해 주세요.')}finally{b.classList.remove('loading');b.innerHTML='<span>✦</span> 이 프롬프트로 이미지 생성'}};
outputEl.oninput=()=>{document.getElementById('wordCount').textContent=`${outputEl.value.trim().split(/\s+/).filter(Boolean).length} words`;document.getElementById('translationState').textContent='직접 수정됨'};loadDraft();renderTabs();renderCard();updatePrompt();
